### ISSUE TITLE
WHY CAN'T I RUN THIS PROGRAM ?????!!!!!

### ISSUE THREAD

**Issue by gho5t5** [epinna/tplmap#123]
![ERROR](https://github.com/user-attachments/assets/9dcadd00-88a4-4d37-af55-29cf62656514)

root@DESKTOP-ULI6RF0:~/tplmap# python3 tplmap.py
Traceback (most recent call last):
  File "/root/tplmap/tplmap.py", line 2, in <module>
    from utils import cliparser
  File "/root/tplmap/utils/cliparser.py", line 163, in <module>
    parser.formatter.format_option_strings = type(parser.formatter.format_option_strings)(_, parser, type(parser))
TypeError: method expected 2 arguments, got 3

**Comment by 0x00650a** [comment]
<h3>**Potential Issue:**</h3>

-  Python Version Compatibility: The code might be written for a different version of Python, and the method signature of format_option_strings could have changed between versions.
<h3>So,</h3>
If the tool is written for an older version of Python you have, you might need to modify it to be compatible with the version you are using.
