### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Teicu** [epinna/tplmap#49]
Hi, can you help me please to fix this error

./bin/pip install PyYaml requests
Downloading/unpacking PyYaml
  Downloading PyYAML-3.13.tar.gz (270kB): 270kB downloaded
  Running setup.py (path:/private/var/folders/bw/396sl31x6pg3bbn9nn0p22x00000gn/T/pip_build_Pentest/PyYaml/setup.py) egg_info for package PyYaml
    
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/path/to/install/jython/Lib/site-packages/pip/basecommand.py", line 133, in main
    status = self.run(options, args)
  File "/path/to/install/jython/Lib/site-packages/pip/commands/install.py", line 316, in run
    requirement_set.prepare_files(
  File "/path/to/install/jython/Lib/site-packages/pip/commands/install.py", line 316, in run
    requirement_set.prepare_files(
  File "/path/to/install/jython/Lib/site-packages/pip/req/req_set.py", line 397, in prepare_files
    req_to_install.assert_source_matches_version()
  File "/path/to/install/jython/Lib/site-packages/pip/req/req_install.py", line 478, in assert_source_matches_version
    version = self.installed_version
  File "/path/to/install/jython/Lib/site-packages/pip/req/req_install.py", line 474, in installed_version
    return self.pkg_info()['version']
  File "/path/to/install/jython/Lib/site-packages/pip/req/req_install.py", line 442, in pkg_info
    data = self.egg_info_data('PKG-INFO')
  File "/path/to/install/jython/Lib/site-packages/pip/req/req_install.py", line 371, in egg_info_data
    data = read_text_file(filename)
  File "/path/to/install/jython/Lib/site-packages/pip/util.py", line 777, in read_text_file
    encodings = ['utf-8', locale.getpreferredencoding(False), 'latin1']
  File "/path/to/install/jython/Lib/locale.py", line 574, in getpreferredencoding
    return getdefaultlocale()[1]
  File "/path/to/install/jython/Lib/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "/path/to/install/jython/Lib/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Storing debug log for failure in /Users/test/.pip/pip.log

**Comment by epinna** [comment]
If you search on Google `ValueError: unknown locale: UTF-8`, it seems some environment variable you have to adjust. However it's clearly not a tplmap error but a pip/python error, I'm closing this.
