### ISSUE TITLE
Install burp_extensions failed!

### ISSUE THREAD

**Issue by Lz1y** [epinna/tplmap#59]
Already installed modules.
```
Lz1y say  ~/OneDrive/tools/web/Burp suite/jython/bin  ./jython -m pip freeze
certifi==2019.6.16
chardet==3.0.4
idna==2.8
PyYAML==5.1.2
requests==2.22.0
urllib3==1.25.3
```
Error log:
```
Traceback (most recent call last):
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension.py", line 1, in <module>
    from burp_extension.burp_extender import BurpExtender
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension/burp_extender.py", line 2, in <module>
    from config_tab import ConfigTab
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension/config_tab.py", line 6, in <module>
    from core.checks import plugins
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/core/checks.py", line 20, in <module>
    from core.channel import Channel
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/core/channel.py", line 1, in <module>
    import requests
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/jython/Lib/site-packages/requests/__init__.py", line 115, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/jython/Lib/site-packages/requests/api.py", line 13, in <module>
    from . import sessions
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/jython/Lib/site-packages/requests/sessions.py", line 27, in <module>
    from .adapters import HTTPAdapter
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/jython/Lib/site-packages/requests/adapters.py", line 44, in <module>
    from urllib3.contrib.socks import SOCKSProxyManager
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/jython/Lib/site-packages/requests/adapters.py", line 44, in <module>
    from urllib3.contrib.socks import SOCKSProxyManager
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/jython/Lib/site-packages/urllib3/contrib/socks.py", line 40, in <module>
    import socks
  File "/Users/ziyiliu/OneDrive/tools/web/Burp suite/jython/Lib/site-packages/urllib3/contrib/socks.py", line 40, in <module>
    import socks
  File "/Users/ziyiliu/Library/Python/2.7/lib/python/site-packages/socks.py", line 267, in <module>
    class _BaseSocket(socket.socket):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str

	at org.python.core.Py.TypeError(Py.java:259)
	at org.python.core.PyFunction.function___new__(PyFunction.java:103)
	at org.python.core.PyFunction$exposed___new__.new_impl(Unknown Source)
	at org.python.core.PyType.invokeNew(PyType.java:494)
	at org.python.core.PyType.type___call__(PyType.java:1706)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:496)
	at org.python.core.Py.makeClass(Py.java:1878)
	at org.python.core.Py.makeClass(Py.java:1839)
	at org.python.core.Py.makeClass(Py.java:1831)
	at socks$py.f$0(/Users/ziyiliu/Library/Python/2.7/lib/python/site-packages/socks.py:294)
	at socks$py.call_function(/Users/ziyiliu/Library/Python/2.7/lib/python/site-packages/socks.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at urllib3.contrib.socks$py.f$0(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/urllib3/urllib3/contrib/socks.py:154)
	at urllib3.contrib.socks$py.call_function(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/urllib3/urllib3/contrib/socks.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at requests.adapters$py.f$0(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/requests/requests/adapters.py:84)
	at requests.adapters$py.call_function(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/requests/requests/adapters.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at requests.sessions$py.f$0(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/requests/requests/sessions.py:758)
	at requests.sessions$py.call_function(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/requests/requests/sessions.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.ensureFromList(imp.java:1024)
	at org.python.core.imp.ensureFromList(imp.java:992)
	at org.python.core.imp.import_module_level(imp.java:986)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at requests.api$py.f$0(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/requests/requests/api.py:149)
	at requests.api$py.call_function(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/requests/requests/api.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at requests$py.f$0(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/requests/requests/__init__.py:131)
	at requests$py.call_function(/private/var/folders/wh/yzv10dl94v74fxnnwsr14yl40000gn/T/pip_build_ziyiliu/requests/requests/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_first(imp.java:870)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at core.channel$py.f$0(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/core/channel.py:8)
	at core.channel$py.call_function(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/core/channel.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromSource(imp.java:396)
	at org.python.core.imp.loadFromSource(imp.java:661)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at core.checks$py.f$0(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/core/checks.py:141)
	at core.checks$py.call_function(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/core/checks.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at burp_extension.config_tab$py.f$0(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension/config_tab.py:103)
	at burp_extension.config_tab$py.call_function(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension/config_tab.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at burp_extension.burp_extender$py.f$0(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension/burp_extender.py:5)
	at burp_extension.burp_extender$py.call_function(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension/burp_extender.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx5.f$0(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension.py:1)
	at org.python.pycode._pyx5.call_function(/Users/ziyiliu/OneDrive/tools/web/Burp suite/tplmap/burp_extension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.bbx.<init>(Unknown Source)
	at burp.c15.a(Unknown Source)
	at burp.rj.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Lz1y** [comment]
Oops... My jython environment about lib path set to local python lib path...
