### ISSUE TITLE
burp extension not working

### ISSUE THREAD

**Issue by testzyrgo** [epinna/tplmap#60]
All requirements are met too, when I add burp extension following error occurs:

	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at utils.loggers$py.f$0(/home/krypton/tplmap/utils/loggers.py:57)
	at utils.loggers$py.call_function(/home/krypton/tplmap/utils/loggers.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at core.plugin$py.f$0(/home/krypton/tplmap/core/plugin.py:29)
	at core.plugin$py.call_function(/home/krypton/tplmap/core/plugin.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at plugins.languages.python$py.f$0(/home/krypton/tplmap/plugins/languages/python.py:90)
	at plugins.languages.python$py.call_function(/home/krypton/tplmap/plugins/languages/python.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.ensureFromList(imp.java:1024)
	at org.python.core.imp.ensureFromList(imp.java:992)
	at org.python.core.imp.import_module_level(imp.java:986)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at plugins.engines.mako$py.f$0(/home/krypton/tplmap/plugins/engines/mako.py:6)
	at plugins.engines.mako$py.call_function(/home/krypton/tplmap/plugins/engines/mako.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at core.checks$py.f$0(/home/krypton/tplmap/core/checks.py:141)
	at core.checks$py.call_function(/home/krypton/tplmap/core/checks.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at burp_extension.config_tab$py.f$0(/home/krypton/tplmap/burp_extension/config_tab.py:103)
	at burp_extension.config_tab$py.call_function(/home/krypton/tplmap/burp_extension/config_tab.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at burp_extension.burp_extender$py.f$0(/home/krypton/tplmap/burp_extension/burp_extender.py:5)
	at burp_extension.burp_extender$py.call_function(/home/krypton/tplmap/burp_extension/burp_extender.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx4.f$0(/home/krypton/tplmap/burp_extension.py:1)
	at org.python.pycode._pyx4.call_function(/home/krypton/tplmap/burp_extension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.a3t.<init>(Unknown Source)
	at burp.gcg.a(Unknown Source)
	at burp.ao3.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Et0hacker** [comment]
same issue 
Traceback (most recent call last):
  File "E:\tqlmap_burp\tplmap-master\burp_extension\burp_extender.py", line 2, in <module>
    from config_tab import ConfigTab
  File "E:\tqlmap_burp\tplmap-master\burp_extension\config_tab.py", line 6, in <module>
    from core.checks import plugins
ImportError: No module named core

	at org.python.core.Py.ImportError(Py.java:334)
	at org.python.core.imp.import_first(imp.java:879)
	at org.python.core.imp.import_module_level(imp.java:964)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1149)
	at org.python.core.imp.importFrom(imp.java:1124)
	at config_tab$py.f$0(E:/tqlmap_burp/tplmap-master/burp_extension/config_tab.py:103)
	at config_tab$py.call_function(E:/tqlmap_burp/tplmap-master/burp_extension/config_tab.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:237)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:657)
	at org.python.core.imp.find_module(imp.java:551)
	at org.python.core.imp.import_next(imp.java:838)
	at org.python.core.imp.import_module_level(imp.java:957)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1149)
	at org.python.core.imp.importFrom(imp.java:1124)
	at org.python.pycode._pyx4.f$0(E:/tqlmap_burp/tplmap-master/burp_extension/burp_extender.py:5)
	at org.python.pycode._pyx4.call_function(E:/tqlmap_burp/tplmap-master/burp_extension/burp_extender.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.a3t.<init>(Unknown Source)
	at burp.gcg.a(Unknown Source)
	at burp.ao3.lambda$panelLoaded$0(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
this is my error code evrything is perfect still getting this error

**Comment by Et0hacker** [comment]
@jx6f @epinna

**Comment by jx6f** [comment]
@testzyrgo 
If the PyYaml package is not installed, the error you pasted will appear.

@Et0hacker 
You loaded different file. Please load `tplmap/burp_extension.py` instead of `tplmap/burp_extension/burp_extender.py`

**Comment by topavankumarj** [comment]
[error.txt](https://github.com/epinna/tplmap/files/4133535/error.txt)
I have installed all the requirements plugins, these are all the installed packages in jython. 
certifi (2019.11.28)
chardet (3.0.4)
idna (2.8)
pip (9.0.1)
PyYAML (5.3)
requests (2.22.0)
setuptools (28.8.0)
urllib3 (1.25.8)

I am still getting an error

**Comment by kr1shn4murt1** [comment]
I had the same issue on windows 10,  I solved it uninstalling pyyaml 

**cd /path/to/install/jython
./bin/pip uninstall PyYaml requests**

Then installing like this:

**wget http://pyyaml.org/download/pyyaml/PyYAML-3.09.tar.gz
tar zxf PyYAML-3.09.tar.gz
cd PyYAML-3.09
jython setup.py --without-libyaml install**

http://oldhammade.net/tip/2013/01/27/installing-pyyaml-for-jython.html 

**jython -m pip freeze**
certifi==2019.11.28
chardet==3.0.4
idna==2.8
PyYAML==3.9
requests==2.22.0
urllib3==1.25.8
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
