### ISSUE TITLE
Help setting up Burp extension on Win10

### ISSUE THREAD

**Issue by HunterOfBounties** [epinna/tplmap#66]
Hi guys,

I need some help setting this up on Win10 Burp. I followed the instructions provided.

1. Succesfully downloaded and installed Jython and required extensions to c:\temp\jython

```
wget https://repo1.maven.org/maven2/org/python/jython-installer/2.7.2/jython-installer-2.7.2.jar
mkdir jython
java -jar jython-installer-2.7.2.jar -s -d c:\temp\jython -t standard
cd jython
bin\pip install PyAml requests

```
2. Set Burp to use created Jython JAR and modules:

![image](https://user-images.githubusercontent.com/51365293/88904193-6fefcf00-d25d-11ea-918c-cd6fa6fbcc30.png)

3. Add TPLmap extension to Burp:
![image](https://user-images.githubusercontent.com/51365293/88904406-b80ef180-d25d-11ea-9a30-cb9f5a334a35.png)

I get this error:

```
Traceback (most recent call last):
  File "C:\Temp\tplmap\burp_extension.py", line 1, in <module>
    from burp_extension.burp_extender import BurpExtender
  File "C:\Temp\tplmap\burp_extension\burp_extender.py", line 2, in <module>
    from config_tab import ConfigTab
  File "C:\Temp\tplmap\burp_extension\config_tab.py", line 6, in <module>
    from core.checks import plugins
ImportError: No module named core

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.import_first(imp.java:1230)
	at org.python.core.imp.import_module_level(imp.java:1361)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at burp_extension.config_tab$py.f$0(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/config_tab.py:103)
	at burp_extension.config_tab$py.call_function(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/config_tab.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromPyClass(imp.java:312)
	at org.python.core.imp.createFromPyClass(imp.java:255)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1161)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at burp_extension.burp_extender$py.f$0(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/burp_extender.py:5)
	at burp_extension.burp_extender$py.call_function(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/burp_extender.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromPyClass(imp.java:312)
	at org.python.core.imp.createFromPyClass(imp.java:255)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1161)
	at org.python.core.imp.import_logic(imp.java:1278)
	at org.python.core.imp.import_module_level(imp.java:1369)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at org.python.pycode._pyx5.f$0(C:/Temp/tplmap/burp_extension.py:1)
	at org.python.pycode._pyx5.call_function(C:/Temp/tplmap/burp_extension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.cbw.<init>(Unknown Source)
	at burp.b7f.a(Unknown Source)
	at burp.f96.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

For some reason, its not loading the modules correctly. Any help would be appreciated.

**Comment by jx6f** [comment]
@HunterOfBounties Please try following commands.

```
./bin/pip uninstall PyYaml requests
./bin/pip install PyYaml==5.1.2 requests==2.22.0
```

**Comment by HunterOfBounties** [comment]
Thanks for helping me. The output of the commands:

```
C:\Temp\jython>bin\pip uninstall PyYaml requests
[33mDEPRECATION: A future version of pip will drop support for Python 2.7.[0m
Uninstalling requests-2.24.0:
  Would remove:
    c:\temp\jython\lib\site-packages\requests-2.24.0.dist-info\*
    c:\temp\jython\lib\site-packages\requests\*
Proceed (y/n)? y
  Successfully uninstalled requests-2.24.0
Uninstalling PyYAML-5.3.1:
  Would remove:
    c:\temp\jython\lib\site-packages\pyyaml-5.3.1-py2.7.egg-info
    c:\temp\jython\lib\site-packages\yaml\*
  Would not remove (might be manually added):
    c:\temp\jython\lib\site-packages\yaml\__init__$py.class
    c:\temp\jython\lib\site-packages\yaml\composer$py.class
    c:\temp\jython\lib\site-packages\yaml\constructor$py.class
    c:\temp\jython\lib\site-packages\yaml\cyaml$py.class
    c:\temp\jython\lib\site-packages\yaml\dumper$py.class
    c:\temp\jython\lib\site-packages\yaml\emitter$py.class
    c:\temp\jython\lib\site-packages\yaml\error$py.class
    c:\temp\jython\lib\site-packages\yaml\events$py.class
    c:\temp\jython\lib\site-packages\yaml\loader$py.class
    c:\temp\jython\lib\site-packages\yaml\nodes$py.class
    c:\temp\jython\lib\site-packages\yaml\parser$py.class
    c:\temp\jython\lib\site-packages\yaml\representer$py.class
    c:\temp\jython\lib\site-packages\yaml\resolver$py.class
    c:\temp\jython\lib\site-packages\yaml\scanner$py.class
    c:\temp\jython\lib\site-packages\yaml\serializer$py.class
    c:\temp\jython\lib\site-packages\yaml\tokens$py.class
Proceed (y/n)? y
  Successfully uninstalled PyYAML-5.3.1

C:\Temp\jython>bin\pip install PyYaml==5.1.2 requests==2.22.0
[33mDEPRECATION: A future version of pip will drop support for Python 2.7.[0m
Collecting PyYaml==5.1.2
[?25l  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
[K     |################################| 266kB 948kB/s eta 0:00:01
[?25hCollecting requests==2.22.0
[?25l  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
[K     |################################| 61kB 2.0MB/s eta 0:00:01
[?25hRequirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\temp\jython\lib\site-packages (from requests==2.22.0) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\temp\jython\lib\site-packages (from requests==2.22.0) (2020.6.20)
Collecting idna<2.9,>=2.5 (from requests==2.22.0)
[?25l  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
[K     |################################| 61kB 2.4MB/s eta 0:00:01
[?25hRequirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\temp\jython\lib\site-packages (from requests==2.22.0) (3.0.4)
Installing collected packages: PyYaml, idna, requests
  Running setup.py install for PyYaml ... [?25ldone
[?25h  Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
Successfully installed PyYaml-5.1.2 idna-2.8 requests-2.22.0
[33mWARNING: You are using pip version 19.1, however version 20.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.[0m
```

Seems to be working, but still get the same error:

```
Traceback (most recent call last):
  File "C:\Temp\tplmap\burp_extension.py", line 1, in <module>
    from burp_extension.burp_extender import BurpExtender
  File "C:\Temp\tplmap\burp_extension\burp_extender.py", line 2, in <module>
    from config_tab import ConfigTab
  File "C:\Temp\tplmap\burp_extension\config_tab.py", line 6, in <module>
    from core.checks import plugins
ImportError: No module named core

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.import_first(imp.java:1230)
	at org.python.core.imp.import_module_level(imp.java:1361)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at burp_extension.config_tab$py.f$0(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/config_tab.py:103)
	at burp_extension.config_tab$py.call_function(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/config_tab.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromPyClass(imp.java:312)
	at org.python.core.imp.createFromPyClass(imp.java:255)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1161)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at burp_extension.burp_extender$py.f$0(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/burp_extender.py:5)
	at burp_extension.burp_extender$py.call_function(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/burp_extender.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromPyClass(imp.java:312)
	at org.python.core.imp.createFromPyClass(imp.java:255)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1161)
	at org.python.core.imp.import_logic(imp.java:1278)
	at org.python.core.imp.import_module_level(imp.java:1369)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at org.python.pycode._pyx5.f$0(C:/Temp/tplmap/burp_extension.py:1)
	at org.python.pycode._pyx5.call_function(C:/Temp/tplmap/burp_extension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.cbw.<init>(Unknown Source)
	at burp.b7f.a(Unknown Source)
	at burp.f96.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by HunterOfBounties** [comment]
Directory c:\temp\tplmap structure:

burp_extension.py
|---/burp_extension
     |---burp_extender.py
     |---channel.py
     |---  ...

**Comment by jx6f** [comment]
Thank you for reporting.

I think that this error means the `tplmap/core` directory does not exist.

```
  File "C:\Temp\tplmap\burp_extension\config_tab.py", line 6, in <module>
    from core.checks import plugins
ImportError: No module named core
```

Does `c:\temp\tplmap\core\checks.py` exist?

**Comment by HunterOfBounties** [comment]
No there weren't any subdirectories under c:\temp\tplmap\burp_extension. Now I copied everything from the root of the repository to folder c:\temp\tplmap\burp_extensions. But we are getting somewhere - as I try to load the extension in Burp, it finds core.checks module, but fails on plugins.engines.mako import:

```
Traceback (most recent call last):
  File "C:\Temp\tplmap\burp_extension.py", line 1, in <module>
    from burp_extension.burp_extender import BurpExtender
  File "C:\Temp\tplmap\burp_extension\burp_extender.py", line 2, in <module>
    from config_tab import ConfigTab
  File "C:\Temp\tplmap\burp_extension\config_tab.py", line 6, in <module>
    from core.checks import plugins
  File "C:\Temp\tplmap\burp_extension\core\checks.py", line 1, in <module>
    from plugins.engines.mako import Mako
ImportError: No module named plugins

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.import_first(imp.java:1230)
	at org.python.core.imp.import_module_level(imp.java:1361)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at burp_extension.core.checks$py.f$0(C:/Temp/tplmap/burp_extension/core/checks.py:141)
	at burp_extension.core.checks$py.call_function(C:/Temp/tplmap/burp_extension/core/checks.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromPyClass(imp.java:312)
	at org.python.core.imp.createFromPyClass(imp.java:255)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1161)
	at org.python.core.imp.import_logic(imp.java:1278)
	at org.python.core.imp.import_module_level(imp.java:1369)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at burp_extension.config_tab$py.f$0(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/config_tab.py:103)
	at burp_extension.config_tab$py.call_function(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/config_tab.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromPyClass(imp.java:312)
	at org.python.core.imp.createFromPyClass(imp.java:255)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1161)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at burp_extension.burp_extender$py.f$0(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/burp_extender.py:5)
	at burp_extension.burp_extender$py.call_function(C:/Users/MarkoN/OneDrive/scripts/burp/tplmap/burp_extension/burp_extender.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:630)
	at org.python.core.imp.createFromPyClass(imp.java:312)
	at org.python.core.imp.createFromPyClass(imp.java:255)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.PyModule.findSubModule(PyModule.java:140)
	at org.python.core.PyModule.impAttr(PyModule.java:107)
	at org.python.core.imp.import_next(imp.java:1161)
	at org.python.core.imp.import_logic(imp.java:1278)
	at org.python.core.imp.import_module_level(imp.java:1369)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1620)
	at org.python.core.imp.importFrom(imp.java:1595)
	at org.python.pycode._pyx5.f$0(C:/Temp/tplmap/burp_extension.py:1)
	at org.python.pycode._pyx5.call_function(C:/Temp/tplmap/burp_extension.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.cbw.<init>(Unknown Source)
	at burp.b7f.a(Unknown Source)
	at burp.f96.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

checks.py, which tries to import mako, is now located at C:\Temp\tplmap\burp_extension\core\checks.py.

mako.py is now located at C:\Temp\tplmap\burp_extension\plugins\engines\mako.py.

**Comment by jx6f** [comment]
You don't need to change the directory structure.
Just download tplmap to `C:\Temp\tplmap` and load `C:\Temp\tplmap\burp_extension.py` by burp suite.

**Comment by HunterOfBounties** [comment]
Oh stupid me! You are absolutely right, now it loads correctly:
![image](https://user-images.githubusercontent.com/51365293/89004820-af74f480-d30b-11ea-80bc-58ce827649d0.png)

I think the installation instructions are a bit hazy here, so if I may suggest, you could add instructions for Win users to download (or git clone) the whole repo.

Thanks again for your quick replies 👍 !
