### ISSUE TITLE
Traceback (most recent call last):   File "tplmap.py", line 2, in <module> 

### ISSUE THREAD

**Issue by litt1eb0yy** [epinna/tplmap#97]
```
littleboy_pugazh@cloudshell:~/tplmap$ python3 tplmap.py
Traceback (most recent call last):
  File "tplmap.py", line 2, in <module>
    from utils import cliparser
  File "/home/littleboy_pugazh/tplmap/utils/cliparser.py", line 163, in <module>
    parser.formatter.format_option_strings = type(parser.formatter.format_option_strings)(_, parser, type(parser))
TypeError: method expected 2 arguments, got 3
```

**Comment by litt1eb0yy** [comment]
littleboy_pugazh@cloudshell:~/tplmap$ python3 tplmap.py -h
Traceback (most recent call last):
  File "tplmap.py", line 2, in <module>
    from utils import cliparser
  File "/home/littleboy_pugazh/tplmap/utils/cliparser.py", line 163, in <module>
    parser.formatter.format_option_strings = type(parser.formatter.format_option_strings)(_, parser, type(parser))
TypeError: method expected 2 arguments, got 3

**Comment by litt1eb0yy** [comment]
Anyone Please give solution for this..

**Comment by Aviksaikat** [comment]
try running with python2

**Comment by litt1eb0yy** [comment]
Yeah. It's now working ✌️
